name: portfolio
description: "company portfolio"
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'

#===================================================

dependencies:
  flutter:
    sdk: flutter

  #================== package ======================
  cupertino_icons:
  url_launcher:
  web:
  http:
  mailer:
  responsive_builder:
  flutter_launcher_icons:
  flutter_animate_on_scroll:
  device_preview:
  widget_and_text_animator: 
  carousel_slider: 
  visibility_detector:
  animated_text_kit:
  card_swiper: 
  stacked_card_carousel: 

#===================================================

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  web:
    generate: true
    image_path: "asset/images/logo-modified.png"

  flutter_lints: ^3.0.0

#===================================================

flutter:
  uses-material-design: true

  assets:
    - asset/images/
    - asset/icon/

  fonts:
   - family: doto
     fonts:
       - asset: asset/font/Doto-all.ttf
#===================================================